###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
description: IBM Integration Bus node
name: iib-helm
version: 0.1.0
icon: https://github.com/ot4i/iib-helm/blob/master/IBM_Integration_Bus_Icon.svg
